$path='src/data/statesData.ts'
$txt=Get-Content -Raw $path
$map = @{
    'Andaman & Nicobar Islands' = '["Lonely"]'
    'Andhra Pradesh' = '[]'
    'Arunachal Pradesh' = '["Calm","Adventurous"]'
    'Assam' = '[]'
    'Bihar' = '[]'
    'Chhattisgarh' = '[]'
    'Delhi' = '["Excited"]'
    'Goa' = '["Happy","Romantic"]'
    'Gujarat' = '[]'
    'Haryana' = '[]'
    'Himachal Pradesh' = '["Sad","Adventurous"]'
    'Jammu & Kashmir' = '["Romantic"]'
    'Jharkhand' = '[]'
    'Karnataka' = '[]'
    'Kerala' = '["Sad","Calm"]'
    'Madhya Pradesh' = '[]'
    'Maharashtra' = '["Excited"]'
    'Manipur' = '[]'
    'Meghalaya' = '["Lonely","Adventurous"]'
    'Mizoram' = '[]'
    'Nagaland' = '[]'
    'Odisha' = '[]'
    'Punjab' = '["Happy"]'
    'Rajasthan' = '["Romantic"]'
    'Sikkim' = '["Sad","Calm"]'
    'Tamil Nadu' = '["Spiritual"]'
    'Telangana' = '["Excited"]'
    'Tripura' = '[]'
    'Uttar Pradesh' = '["Spiritual"]'
    'Uttarakhand' = '["Lonely","Spiritual"]'
    'West Bengal' = '["Happy"]'
}
foreach($k in $map.Keys){
    $txt = [regex]::Replace($txt, '(name:\s*"' + [regex]::Escape($k) + '"[\s\S]*?moods:\s*)\[[^\]]*\]', '${1}' + $map[$k], 'Singleline')
}
Set-Content -Path $path -Value $txt
Write-Host 'Updated moods for ' + $map.Count + ' states'